# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [79]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [80]:
filepath = '../WeatherPy/cities.csv'
city_data = pd.read_csv(filepath)
city_data

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,upernavik,72.7868,-56.1549,16.52,87,100,9.17,GL,1668907471
1,1,leningradskiy,69.3833,178.4167,-12.87,98,100,5.75,RU,1668907471
2,2,pevek,69.7008,170.3133,-16.73,100,99,7.58,RU,1668907471
3,3,port augusta,-32.5000,137.7667,69.30,32,6,18.54,AU,1668907472
4,4,bonavista,48.6499,-53.1147,34.36,62,46,20.80,CA,1668907473
...,...,...,...,...,...,...,...,...,...,...
573,573,dabat,12.9842,37.7650,53.04,59,6,4.41,ET,1668907755
574,574,cap-aux-meules,47.3821,-61.8597,28.45,74,20,5.75,CA,1668907757
575,575,banjar,-8.1900,114.9675,84.13,70,91,3.29,ID,1668907758
576,576,galveston,29.3669,-94.9669,46.49,91,100,1.99,US,1668907758
577,577,lazaro cardenas,17.9583,-102.2000,78.66,78,98,4.70,MX,1668907732

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [81]:
gmaps.configure(api_key=g_key)

In [82]:
locations = city_data[['Lat', 'Lng']]
fig = gmaps.figure(zoom_level = 2,center = (46,-5))
heat_layer = gmaps.heatmap_layer(locations, weights = city_data['Humidity'])
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [83]:
fit_weather = city_data.loc[(city_data["Max Temp"] < 85) & (city_data["Humidity"] < 50) & (city_data["Wind Speed"] < 10) & (city_data["Cloudiness"] < 60)]
fit_weather.dropna()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
14,14,mataura,-46.1927,168.8643,72.18,47,52,3.44,NZ,1668907478
35,35,devli,25.7500,75.3833,59.92,44,0,3.62,IN,1668907487
67,67,binga,-17.6203,27.3414,75.97,33,1,1.34,ZW,1668907501
74,74,kodinar,20.7903,70.7031,69.37,39,0,9.44,IN,1668907504
111,111,chibombo,-14.6569,28.0706,67.08,44,6,2.98,ZM,1668907525
118,118,half moon bay,37.4636,-122.4286,60.98,47,0,6.91,US,1668907528
136,136,myre,69.1036,15.9492,30.15,45,0,6.53,NO,1668907537
160,160,chiredzi,-21.0500,31.6667,76.14,33,5,3.98,ZW,1668907429
237,237,saint-louis,16.3333,-15.0000,76.48,13,8,9.48,SN,1668907588
246,246,taoudenni,22.6783,-3.9836,72.52,12,0,9.64,ML,1668907593
247,247,saint george,37.1041,-113.5841,46.99,30,0,4.61,US,1668907575
261,261,biltine,14.5333,20.9167,69.71,22,5,8.12,TD,1668907600
295,295,yuba city,39.1405,-121.6169,57.33,42,0,0.00,US,1668907615
311,311,mount darwin,-16.7725,31.5838,73.92,46,6,2.71,ZW,1668907623
322,322,upington,-28.4478,21.2561,59.38,36,0,1.14,ZA,1668907630
347,347,batangafo,7.3008,18.2833,73.44,48,19,2.33,CF,1668907643
353,353,farmington,36.7281,-108.2187,34.77,38,0,5.75,US,1668907452
373,373,skjervoy,70.0311,20.9714,24.80,43,0,7.11,NO,1668907654
386,386,garmsar,35.2182,52.3409,52.43,38,5,2.59,IR,1668907660
395,395,mangrol,21.1167,70.1167,70.93,39,0,9.40,IN,1668907665
397,397,amarillo,35.2220,-101.8313,36.68,34,0,3.44,US,1668907607
480,480,joshimath,30.5667,79.5667,46.08,41,1,6.89,IN,1668907709
496,496,mandalgovi,45.7625,106.2708,14.07,45,10,4.56,MN,1668907717
517,517,tafresh,34.6920,50.0130,41.88,42,4,2.06,IR,1668907726
532,532,jaisalmer,26.9147,70.9181,68.58,35,42,6.78,IN,1668907734
554,554,san joaquin,37.9333,-121.3011,59.11,48,0,0.00,US,1668907744
556,556,agadir,30.4202,-9.5982,55.85,46,6,5.35,MA,1668907671
570,570,dwarka,22.2394,68.9678,74.80,47,0,5.12,IN,1668907751

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [122]:
hotel_df = fit_weather[['City', 'Lat', 'Lng', 'Country']]
hotel_df['Hotel Name'] = ""
params={'radius': 5000, 'types': 'lodging','key':g_key}
for index, row in hotel_df.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    response = requests.get(base_url, params = params)
    response_json = response.json()
    try:
        hotel_df.loc[index, "Hotel Name"] = response_json["results"][0]["name"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

C:\Users\brian\AppData\Local\Temp\ipykernel_26308\3839689669.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df['Hotel Name'] = ""

Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.

In [123]:
hotel_df

,City,Lat,Lng,Country,Hotel Name
14,mataura,-46.1927,168.8643,NZ,Ellie's Villa
35,devli,25.7500,75.3833,IN,HOTEL DWARKA PALACE
67,binga,-17.6203,27.3414,ZW,Lakeview Inn Binga
74,kodinar,20.7903,70.7031,IN,residency of N.B vadhel
111,chibombo,-14.6569,28.0706,ZM,Chibombo District Council Guest House
118,half moon bay,37.4636,-122.4286,US,"The Ritz-Carlton, Half Moon Bay"
136,myre,69.1036,15.9492,NO,Arlistua
160,chiredzi,-21.0500,31.6667,ZW,Clevers Hotel Chiredzi
237,saint-louis,16.3333,-15.0000,SN,
246,taoudenni,22.6783,-3.9836,ML,
247,saint george,37.1041,-113.5841,US,Best Western Plus Abbey Inn
261,biltine,14.5333,20.9167,TD,Hôtel Trois Étoiles de Biltine
295,yuba city,39.1405,-121.6169,US,Bonanza Inn & Suites Yuba City
311,mount darwin,-16.7725,31.5838,ZW,
322,upington,-28.4478,21.2561,ZA,River Place Manor
347,batangafo,7.3008,18.2833,CF,OCHA Office
353,farmington,36.7281,-108.2187,US,Courtyard by Marriott Farmington
373,skjervoy,70.0311,20.9714,NO,Tschudi Marine Services AS
386,garmsar,35.2182,52.3409,IR,مجتمع مرصاد
395,mangrol,21.1167,70.1167,IN,Hotel The Royal Honours
397,amarillo,35.2220,-101.8313,US,Microtel Inn & Suites by Wyndham Amarillo
480,joshimath,30.5667,79.5667,IN,Shivalik Camps & Resort
496,mandalgovi,45.7625,106.2708,MN,В.Ганбат
517,tafresh,34.6920,50.0130,IR,هتل یاس سفید
532,jaisalmer,26.9147,70.9181,IN,Hotel Fifu
554,san joaquin,37.9333,-121.3011,US,University Plaza Waterfront Hotel
556,agadir,30.4202,-9.5982,MA,Iberostar Founty Beach
570,dwarka,22.2394,68.9678,IN,Hotel Narayan Avezika Comfort

In [126]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [132]:
# Add marker layer ontop of heat map
bank_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=[f"Hotel: {hotel}" for hotel in hotel_df['Hotel Name']]
)


fig = gmaps.figure()
fig.add_layer(bank_layer)


# Display figure
fig

Figure(layout=FigureLayout(height='420px'))